Update README

diff --git a/.github/workflows/muilt.yml b/.github/workflows/muilt.yml
--- a/.github/workflows/muilt.yml
+++ b/.github/workflows/muilt.yml
@@ -74,20 +74,30 @@ jobs:
         # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
         run: ctest --build-config ${{ matrix.build_type }}
 
-      - name: Run Executable
+      - name: Run Executables and Analyze
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         shell: bash
         run: |
-          if [ "$RUNNER_OS" == "Windows" ]; then
-            executable_name="${{ matrix.build_type }}/main.exe"
-          else
-            executable_name="main"
-          fi
+          executables=("main" "main_async")
 
-          if [ -f "$executable_name" ]; then
-            "./$executable_name" 
-          else
-            echo "Executable not found at: $executable_name"
-            exit 1
-          fi
-          
+          for exe in "${executables[@]}"; do
+              executable_name=""
+
+              if [ "$RUNNER_OS" == "Windows" ]; then
+                executable_name="${{ matrix.build_type }}/${exe}.exe"
+              else
+                executable_name="${exe}"
+              fi
+
+              # --- Run the executable with all required arguments ---
+              if [ -f "${executable_name}" ]; then
+                if [ "$RUNNER_OS" == "Windows" ]; then
+                  powershell -Command "& \"${executable_name}\"" || true
+                else
+                  "./$executable_name"  || true
+                fi
+              else
+                echo "Error: Executable not found: $(pwd)/${executable_name}"
+                exit 1
+              fi
+          done
